test basic notebook and nbconvert to pdf

diff --git a/postBuild b/postBuild
--- a/postBuild
+++ b/postBuild
@@ -32,4 +32,12 @@ done
               echo "Error: PDF conversion failed for $notebook"
               exit 1
           fi
-      done
+
+# Test if notebook can be converted to pdf
+for notebook in image-tests/*.ipynb; do
+    jupyter nbconvert --to webpdf "$notebook"
+    if [ ! -f "${notebook%.ipynb}.pdf" ]; then
+        echo "Error: PDF conversion failed for $notebook"
+        exit 1
+    fi
+done
